// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igvhdbbpuhygsaidjkiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlndmhkYmJwdWh5Z3NhaWRqa2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Njc5MDksImV4cCI6MjA3MDI0MzkwOX0.PsiMRiycAmkl8k97WmyaOA0s6DcJaPwcK5Gjrioz0ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});